Enabled: true
Output Dir: proxies
Git:
  email: felicia@realnet.ml
  name: FeliciaWen
SCServer: 127.0.0.1:25500
SCServerRemote: api.wcc.best
Storage: realnet.ga
ProxyProviders:
  YahahaNPO: http://sub.yahahanpo.top/link/MPsna0K3Q1JBfwNf?mu=1
  YahahaLTD: http://yahahasub.com/link/GNMR6Hv4UNg8KdrG?mu=0
  Sakura: https://subscribe.connect-node.xyz/link/eYXuRuK1xeeD2Z2H?clash=1
  Getfree: https://rss.getfree.win/link/8FF08IStcxG8RIRe?sub=1
  ADSL: https://rss.epon.cloud/link/Vasve5Pu5e6UPZWp?sub=1
  ChinaG: https://a.luxury/link/1EqOeAkeI5cjbRnt?clash=2
  JDYun: https://www.somersaultcloud.xyz/link/XqieypOBFUfvSa8l?sub=3&extend=1
ClashProviders:
  target: clash
  list: true
  udp: true
  emoji: true
  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
ExcludeExp: 
  syntax: 奈飞小铺|过期时间|剩余流量|官网|机场|维护
  whitelist: 
  - ChinaG
QuickGenQX: true
SmartFilter: 
  ChinaG: \d*\.*\d+(?:x|X|倍|倍率)
  YahahaLTD: \d*\.*\d+(?:x|X|倍|倍率)|限速|Game|游戏|原生|IEPL|IPLC
Rules:
  Clash:
    head: template/clash/head.yml
    rules: template/clash/connershua/rules.yml 