Enabled: true
Output Dir: proxies
Git:
  email: felicia@realnet.ml
  name: FeliciaWen
SCServer: 127.0.0.1:25500
SCServerRemote: api.wcc.best
Storage: https://realnet.ga
Template: ./template/clash
ProxyProviders:
  YahahaNPO: http://sub.yahahanpo.top/link/MPsna0K3Q1JBfwNf?mu=1
  YahahaLTD: http://yahahasub.com/link/oSmrgjMRXcAcz0O8?mu=0
  Sakura: https://subscribe.connect-node.xyz/link/qSJlYVsRF85rIGWC?sub=3
  Getfree: https://rss.getfree.win/link/WXdDzEXi5DVXpOc1?sub=1
  ADSL: https://rss.epon.cloud/link/wRa8eyB5WguX7iOM?sub=1
  ChinaG: https://a.luxury/link/cHDgH9k2VEv56gkv?clash=2
  JDYun: https://www.somersaultcloud.xyz/link/4bQZhQtwqOboaFvP?sub=3&extend=1
ClashProviders:
  target: clash
  list: true
  udp: true
  emoji: true
  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
Exclude:
  All: 限速|游戏|game
  region: 限速|游戏|game
Exclude Args: 
  syntax: 奈飞小铺|过期时间|剩余流量|官网|机场|维护
  whitelist: 
  - ChinaG
QuickGenQX: true
SmartFilter: 
  ChinaG: \d*\.*\d+(?:x|X|倍|倍率)
  YahahaLTD: \d*\.*\d+(?:x|X|倍|倍率)|限速|Game|游戏|原生|IEPL|IPLC
Rules:
  Clash:
    head: template/clash/head.yml
    rules: template/clash/connershua/rules.yml 